### ISSUE TITLE
Have it's support upload from url ?

### ISSUE THREAD

**Issue by huyhvq** [dfmedia/dfm-smug-wrapper#3]
Hi,
have smugmug api v2 support upload from url ? and I want to use your library to my laravel project and i would like to convert it's to a packages of laravel, have you support me ?
thank you.

**Comment by NFabrizio** [comment]
@heoquay99, SmugMug API v2.0 does support upload from URI by using the endpoint of the format http://api.smugmug.com/api/v2/album/<your_album_key>!uploadfromuri. However, the DFM Smug Wrapper does not currently handle this method. 

Currently, we are not actively supporting this package, but you are free to take the code and make any changes to it that you would like under the GPLv3 license.

**Comment by huyhvq** [comment]
hi @NFabrizio  i see your plugin has parameter token_id and token_secret and i don't know where to find it's ? :( sorry my first time working with oauth 1.0.

**Comment by NFabrizio** [comment]
@heoquay99, you can find some useful information in the README file under the Authentication section at https://github.com/dfmedia/dfm-smug-wrapper/blob/master/README.md#authentication. Using OAuth is a multiple step process in which you will send requests to SmugMug, and SmugMug will send a response back with information you need to send in your next request. An important thing to keep in mind is that with OAuth, the user of your application must be sent to SmugMug to log in and grant your application access to their account at some point.
