### ISSUE TITLE
Doesn't work with cURL

### ISSUE THREAD

**Issue by BarryBahrami** [dfmedia/dfm-smug-wrapper#8]
Hello,

This doesn't work at all with cURL.  It seems to want to use a wordpress function.  I don't have wordpress installed.  I do see code for cURL but there is one part that doesn't support it - go figure the upload I'm trying to complete. heh

code says:

// Use the WP function instead of cURL so we don't run into any issues.
		// ^^^ Use if/else for cUrl
	
		$response = wp_remote_get( $this->url, $http_header );

but there is nothing further for cURL.

as a result, the error given is:

PHP Fatal error:  Uncaught Error: Call to undefined function wp_remote_get()

thank you

**Comment by davidvexel** [comment]
hi @BBSDCA , this plugin was built to work on top of WordPress, if you're not using this framework, I'd suggest you to use the PHP library we're using: http://phpsmug.com/

Regards.
